= LUA
Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
:toc:
:toclevels: 4
:numbered:
:toc-placement!:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

:ddir: https://wimalopaan.github.io/LUA
:rcb: {ddir}/rc/boards

toc::[]

== MultiSwitch-Widget

EdgeTx LUA Widget for ELRS MultiSwitch

== Hardware-Extension-Widget

EdgeTx LUA Widget for the `hardware-extension`-protocol.

== Mixer-Script `crsfch.lua`

EdgeTx mixer script `crsfch.lua`.
Sends additional channels (up to 32) to FC

== Widget for RC720E32 (Schottel-Controller)

EdgeTx LUA Widget for the Schottel-Controller `RC720E32`

== Voith-Schneider EdgeTx / OpenTx LUA mixer script 

This is a limiter script `vsp.lua` for controlling Voith-Schneider propellers. It incorporates an
additional correction algorithm. This is neccessary due to the geometry of the fixed rectangular servo configuration.

== Incremental mixer script

The `increm.lua` mixer script implements an incremental channel: an output value that is the integral (sum over time) of 
the choosen input scaled with some (speed) factor.
