= LUA
Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
:toc:
:toclevels: 4
:numbered:
:toc-placement!:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

:ddir: https://wimalopaan.github.io/LUA
:rcb: {ddir}/rc/boards

toc::[]

== MultiSwitch-Widget

EdgeTx LUA Widget for ELRS MultiSwitch

== Hardware-Extension-Widget `lvglHwExt`

EdgeTx LUA Widget for the `hardware-extension`-protocol.
(The current version need EdgeTx PR 5885)

== Mixer-Script `crsfch.lua`

EdgeTx mixer script `crsfch.lua`.
Sends additional channels (up to 32) to FC

== LVGL MultiSwitch Widget `lvglMultiSW`

New widget for the MultiSwitch-E32 based on LVGL UI controls.

== LVGL Controls Widget `lvglControls`

This widget shows up to 16 _virtual sources_ (sliders). The values of these controls are stored in
Shared-Memory variables. These variables can be uses via <<shm.lua>>.

[[shm.lua]]
== Mixer-Script `shm.lua`

Reads up to 6 Shared-Memory-Variables and outputs them _without_ any processing. 
This is usesful to use the Shared-Memoty-Variables as mixer-inputs.

== Widget for RC720E32 (Schottel-Controller)

EdgeTx LUA Widget for the Schottel-Controller `RC720E32`

== Voith-Schneider EdgeTx / OpenTx LUA mixer script 

This is a limiter script `vsp.lua` for controlling Voith-Schneider propellers. It incorporates an
additional correction algorithm. This is neccessary due to the geometry of the fixed rectangular servo configuration.

== Incremental EdgeTx / OpenTx mixer script

The `increm.lua` mixer script implements an incremental channel: an output value that is the integral (sum over time) of 
the choosen input scaled with some (speed) factor. This sometimes called hydraulic-simulation.

== EdgeTx Simulator

As of version 2.11 the EdgeTx simulator supports using host serial ports (e.g. USB/serial adapters) as AUX1/2 in the simulator. These serial ports can be used for all purposes but for internal/external module connection.

Connecting an ELRS-module (e.g. a rx-as-tx) via USB/serial is easy. One can also use a ELRS-module with USB, if you tweak the internal pin connection of UART1 to the USB.

Now the `crsf16.lua` script can send CRSF packets out of the serial to the ELRS-module. Then this module connects to the receiver (if already bound).

To make configuration changes you need a modified version of `elrsV3.lua` that also uses the serial instead of the internal/external modul connection (which is not working on simulator).

=== CRSF channels mixer script 

The `crsf16.lua` mixer script sends the first 16 channels over serial (921600 baud).

=== ELRSV3 for simulator: `elrsV3simu.lua`

Adaption of the `elrsv3.lua` to send/receive CRSF packets over serial (921600 baud).

=== `crossfireTelemetry...()` replacement

The `elrsV3simu.lua` uses LUA implementations of `crossfireTelemetryPop()` and `crossfireTelemetryPush)()`. These replacements are broken out into the `crsfserial.lua` (in `WIDGETS/Schottel`). 
Other scripts can load this file and make use of these functions, so that LUA widgets using crossfire telemetry will also work on `simulator`. Please refer to `elrsV3simu.lua` or
`WIDGETS/Schottel/main.lua` to see how to use them.

